#####
#  GitHub Pages / Jekyll settings / config

headers:
  title:     Shower Presentation Template
  author:    "Vadim Makeev, Opera Software"
  cover:     pictures/cover.jpg
  lang:      en-US
  generator: GitHub Pages w/ Jekyll
  theme:     material


collections:
  slides:
    output: false


exclude:
- README.md
- BUILD.md
- sample.md
- shower.txt
